apiVersion: v1
kind: Service
metadata:
  name: pdfgeneration-eap-service
  namespace: commonservices
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    {{- include "pdf.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: pdf-service-nodeport
  namespace: commonservices
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pdf.selectorLabels" .| nindent 4 }}
  ports:
    - name: console
      port: 9990
      targetPort: 9990
