apiVersion: v1
kind: Service
metadata:
  namespace: helmproduct
  name: renter-service
  labels:
    {{- include "renter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "renter.selectorLabels" . | nindent 4 }}
