apiVersion: v1
kind: Service
metadata:
  name: multitenant
  namespace: pmt
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    {{- include "pmt-multikb.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: multienant-nodeport
  namespace: pmt
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pmt-multikb.selectorLabels" .| nindent 4 }}
  ports:
    - name: console
      port: 9990
      targetPort: 9990
