apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "raas-eap.fullname" . }}
  namespace: helmproduct
  labels:
      # app: raas-eap
      {{- include "raas-eap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      #  app: raas-eap
      {{- include "raas-eap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        #app: raas-eap
        {{- include "raas-eap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
         - name: {{ .Chart.Name }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           env:          
             {{- range .Values.env }}
             - name: {{ .name }}
               value: "{{ .value }}"
             {{- end }}
             - name: sysdbip
               value: "{{ .Values.global.env.sysdbip}}"
             - name: prddbip
               value: "{{ .Values.global.env.prddbip}}"
             - name: logdbip
               value: "{{ .Values.global.env.logdbip}}"
             - name: sysdbport
               value: "{{ .Values.global.env.sysdbport}}"
             - name: prddbport
               value: "{{ .Values.global.env.prddbport}}"
             - name: logdbport
               value: "{{ .Values.global.env.logdbport}}" 
           ports:
             - containerPort: 9990
             - containerPort: 8080
             - containerPort: 8443
           resources:
             {{- toYaml .Values.resources | nindent 12 }}
           volumeMounts:
           - name: transmount
             mountPath: /opt/SharedData/Shared/Solartis/Transaction/
      volumes:
         - name: transmount
           persistentVolumeClaim:
             claimName: {{ .Values.volumes.claimname}} 
