{{- if .Values.ingress.enabled -}}
{{- $fullName := include "raas-eap.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "raas-eap.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: helmproduct
spec:
  tls:
    - hosts:
        - {{ $.Values.ingress.host | quote }}
      secretName: {{ $.Values.ingress.tlssecret }}
  rules:
    - host: {{ $.Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: raas-eap-service
              servicePort: 8080
{{- end }}
