{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: helm-nfs-pvc
  namespace: helmproduct
  labels: {{- include "raas-eap.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode}}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  volumeName: helm-nfs-pv
{{- end }}
