apiVersion: v1
kind: Service
metadata:
  name: raas-eap-service
  namespace: helmproduct
spec:
  type: {{ .Values.service.type }}
  selector:
  #  app: raas-eap
  {{- include "raas-eap.selectorLabels" . | nindent 4 }}
  ports:
    - name: runtime
      #protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      #protocol: TCP
      port: 8443
      targetPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: raas-eap-service-nodeport
  namespace: helmproduct
spec:
  type: {{ .Values.service.type }}
  selector:
    #app: raas-eap
  {{- include "raas-eap.selectorLabels" . | nindent 4 }}
  ports:
    - name: console
      port: 9990
      targetPort: 9990

