# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: iad.ocir.io/solartis/platformservices/email
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v10"

imagePullSecrets:
  - name: oke-registry
nameOverride: ""
fullnameOverride: ""

env:
  - name: timeout
    value: "3000"
  - name: sysdbip
    value: "10.50.0.3"
  - name: prddbip
    value: "10.50.0.3"
  - name: logdbip
    value: "10.50.0.3"
  - name: sysdbport
    value: "3401"
  - name: prddbport
    value: "3402"
  - name: logdbport
    value: "3501"
  - name: smtp-server
    value: "smtp.solartis.in"
  - name: smtp-port
    value: "25"
  - name: smtp-user
    value: "noreply_qa.solartis.in"
  - name: smtp-passwd
    value: "Jan2019"


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - port: 9990
      name: console
      targetPort: 9990
    - port: 8080
      name: http
      targetPort: 8080
    - port: 8443
      name: https
      targetPort: 8443

ingress:
  enabled: false
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
    # kubernetes.io/tls-acme: "true"

resources:
  limits:
      cpu: "3000m"
  requests:
      cpu: "1000m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes:
    claimname: helm-common-pvc

persistence:
  enabled: false
  storageClass: oci-fss
  accessMode: ReadWriteMany
  size: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}
